apiVersion: compute.cnrm.cloud.google.com/v1beta1 
kind: Network
metadata:
  name: my-custom-network
spec:
  name: my-custom-network
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: Subnetwork
metadata:
  name: my-custom-subnetwork
spec:
  name: my-custom-subnetwork
  networkRef:
    name: my-custom-network
  ipCidrRange: 10.0.0.0/24
  region: us-central1
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: Instance
metadata:
  name: my-vm-instance
spec:
  name: my-vm-instance
  zone: us-central1-a
  machineTypeRef:
    name: n1-standard-1
  disks:
    - boot: true
      initializeParams:
        image: projects/debian-cloud/global/images/family/debian-10
  networkInterfaces:
    - networkRef:
        name: my-custom-network
      subnetworkRef:
        name: my-custom-subnetwork
  tags:
    items:
      - my-tag
  labels:
    environment: dev
